version: '3.8'

services:
  mysql:
    container_name: 'mysql'
    build:
      context: './docker/mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD:-secret}'
      MYSQL_USER: '${MYSQL_USER:-admin}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD:-admin}'
    ports:
      - '${FORWARD_MYSQL_PORT-10000}:3306'
    volumes:
      - './docker/data/mysql:/var/lib/mysql'
  phpmyadmin:
    container_name: 'phpmyadmin'
    build:
      context: './docker/phpmyadmin'
    restart: 'unless-stopped'
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: '${PHPMYADMIN_UPLOAD_LIMIT:-2000M}'
    depends_on:
      - mysql
    ports:
      - '${FORWARD_PHPMYADMIN_PORT-10001}:80'
  php:
    container_name: 'php'
    build:
      context: './docker/php-fpm'
    volumes:
      - './:/var/www/site'
      - './docker/php-fpm/xdebug/xdebug-default.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    depends_on:
      - mysql
  nginx:
    container_name: 'nginx'
    build:
      context: './docker/nginx'
    ports:
      - '${FORWARD_NGINX_PORT-10002}:80'
    volumes:
      - './:/var/www/site'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
